image: dettmering/hugo-build

variables:
 GIT_SUBMODULE_STRATEGY:
    recursive

pages:
  script:
  - hugo
  - cp -r .well-known public
  artifacts:
    paths:
    - public
  only:
  - master
  
test:
  script:
  - hugo
  except:
  - master
