image: dettmering/hugo-build

pages:
  script:
  - hugo
  - cp -r .well-known public
  artifacts:
    paths:
    - public
  only:
  - master
  
test:
  script:
  - hugo
  - cp -r .well-known public
  except:
  - master
