image: node:latest

cache:
  paths:
   - node_modules/
   - .yarn

before_script:
  - yarn install

pages:
  only:
   - master
  script:
   - node_modules/gulp-cli/bin/gulp.js build
  artifacts:
    paths:
    - public
    expire_in: 1 week
