image: registry.gitlab.com/jasperro/jasperrowebsite-dockercontainer:latest

pages:
  script:
    - make
  artifacts:
    paths:
      - public
  only:
    - master

test:
  script:
    - make
  except:
    - master
