image: registry.gitlab.com/jasperro/jasperrowebsite-dockercontainer:latest

pages:
  stage: deploy
  script:
    - make
    - mkdir .public
    - mv * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master

test:
  script:
    - make
  except:
    - master
