baseurl = "jasper.albering.nl/"
languageCode = "en-us"
relativeURLS=true
DefaultContentLanguage = "en-us" # change to your language
title = "Jasper Albering's Website"
theme = "jasperro"

canonifyurls = true
paginate = 6 # default number of pages per page in pagination

[params]
    description = "Jasper Albering's personal website"
    keywords = "programming"
    customcss = ["/font/Roboto/stylesheet.css"]

[author]
    name = "Jasper Albering"

[permalinks]
    blog = "/blog/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

#[[menu.main]]
#    name = "Blog"
#    url = "/blog/"
#    weight = 2
#[[menu.main]]
#    name = "Portfolio"
#    url = "/portfolio/"
#    weight = 3
